### ISSUE TITLE
update jimp

### ISSUE THREAD

**Issue by nothingismagick** [Iwasawafag/node-potrace#4]
jimp is installed as 0.2.28, but [0.5.3](https://github.com/oliver-moran/jimp/releases/tag/v0.5.3) is available.

**Comment by iwsfg** [comment]
Fixed in #5

**Comment by Sirs0ri** [comment]
I'd like to bump this once again. jimp has seen [a couple new releases](https://github.com/oliver-moran/jimp/releases) since this issue was addressed last time, and the version of jimp required by potrace has old dependencies that now throw warnings in yarn:

`warning @quasar/quasar-app-extension-icon-genie > potrace > jimp > @jimp/plugins > @jimp/plugin-resize > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for 
usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

The old dependency mentioned in the log was fixed [here, in November](https://github.com/oliver-moran/jimp/pull/815), so I'd appreciate it if you could look into this!

Please let me know if you'd like me to open a new issue for this instead of reviving this one.
